### ISSUE TITLE
New feature: Objects

### ISSUE THREAD

**Issue by FreshMag** [mini-roostico/subjekt#103]
Handle object-oriented parameters, accessible via dot access

e.g.

```yaml
parameters:
   - name: days
     values:
     - fullName: Monday
       shortName: Mon
       index: 0

...

${{ days.shortName }}

```
