### ISSUE TITLE
Slice utility

### ISSUE THREAD

**Issue by FreshMag** [mini-roostico/subjekt#83]
e.g. if I have a parameter named `param`, I can do `param[1]` to only include value of index 1, or I can do `param[1:3]` to perform slices

**Comment by FreshMag** [comment]
### Update July 5:

The way slices can be handled is not trivial since in reality Subjekt has 2 possible interpretations of a slice:

#### 1.  **View or Projection** slices
These ones can only act as a "subset" of a parameter, meaning that their indices must be _non-resolvable_ and already defined (i.e. for now this means they must be literals essentially)

```yaml
parameters:
- name: par1
  values: [a, b, c]

subjects:
- "${{ par1[1:2] }}"
```

This restrains Subjekt to use only a fraction of a parameter's values. It can be interpreted as defining a whole new parameter with less values.

This kind of slices can be processed statically, when the context are built from permutations

#### 2. "Cartesian" slices
These slices are kind of powerful, but the current architecture of Subjekt makes it difficult to implement them. Cartesian slices generate new subtrees of contexts starting from an already built one, leading to an exponential growth of the results. 

These slices can have resolvables in their indices, essentially making their projections **depend** on the current context that is being evaluated. For this reason, they can only be evaluated at runtime. 

Allowing them into Subjekt would potentially increase the library's capabilities, but currently its design doesn't allow such a behavior to be implemented easily without rethinking it a bit. 

```yaml
parameters:
- name: par1
  values: [a, b, c, d, e, f]
- name: index
   values: [4, 3, 2]

subjects:
- "Res = ${{ par1[index:5] }}"
```

The previous example should produce these results:
- Res = f (obtained 3 times)
- Res = e (obtained 3 times)
- Res = d (obtained 2 times)
- Res = c (obtained 1 time)
